name: pocketa
description: "Clean Architecture-based Expense Management App built with Flutter, Riverpod, and Hive for offline-first personal finance tracking."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  go_router: ^16.2.0
  intl: ^0.20.2
  uuid: ^4.5.1
  logger: ^2.6.1
  google_fonts: ^6.3.0

  # Freezed + JSON (stable combo with hive_generator)
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1


flutter:
  assets:
    - assets/
    
  uses-material-design: true
  generate: true
