name: pocketa
description: "Pocketa is on of most easy and "
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & State
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  flutter_hooks: ^0.21.2
  shared_preferences: ^2.5.3


  # UI/UX Helpers
  #  responsive_framework: ^1.5.1
  animations: ^2.0.11
  fl_chart: ^1.0.0
  flutter_form_builder: ^10.0.1
  flex_color_scheme: ^8.2.0
  cupertino_icons: ^1.0.8
  country_currency_pickers: ^3.0.0
  country_flags: ^3.2.0
  currency_code_to_currency_symbol: ^0.0.4

  # Dev Tools
  mocktail: ^1.0.4
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  generate: true